### ISSUE TITLE
Stand-up one-refine Design Concept & Low-fideity Prototype

### ISSUE THREAD

**Issue by motaA0309** [motaA0309/Vitality-Ventures#1]
# **Description**
## **Task**
Task 1: Introduction wiki Page
Task 2: Document and Summarize User Interview & Observation (Wiki pages)
Task 3: Complete the Low-fidelity Prototype & Storyboard

## **Example**
 **Interview**: Aggregate questionnaire and interview data to deeper look into the problem space and domain and refine the inital design concept
- **Determine the main features and low-fidelity prototype**:  define serveral main fearures and corresponding interfaces and interactive process

# **Milestones**
Steps that need to be completed for this task:
- [x] Step 1: Design the interview questions and the observation instruction and ready to use (Aug. 28)
- [x] Step 2: Aggregate interview data and observation data and create a document on wiki for other members of the team to view (Sep. 4)
- [x] Step 3: Complete the inital low-fidelity prototype & storyboard (Sep. 08)

**Completion Deadline:** Sep. 08

# **Documentation**
- [Home](https://github.com/motaA0309/Vitality-Ventures/wiki/)
- [Interview](https://github.com/motaA0309/Vitality-Ventures/wiki/User-Interview-Stage1)
- [Observation](https://github.com/motaA0309/Vitality-Ventures/wiki/User-Research-Observation-Stage1)
- [Low-fidelity](https://github.com/motaA0309/Vitality-Ventures/wiki/Low%E2%80%90fidelity-Prototype-and-Storyboard)
 
# **Member**
- Kexin Du (@motaA0309 ) (Kexin Du)
- Chong Xue (@heyitschang ) （Chong Xue)
- Xinyue Li (@lxy-914  ) (Xinyue Li)
- Xinyi Liao (@lxy02230423) (Xinyi Liao）
- Liuwenxuan Yan (@yanlwx) (Liuwenxuan Yan)
