### ISSUE TITLE
Stand-up 2 WEEK10 Update Design Concept & Prototype + Ethical Considerations

### ISSUE THREAD

**Issue by motaA0309** [motaA0309/Vitality-Ventures#2]
# **Description**
## **Task**
Task 1: Update Introduction wiki Page(Kasey)
Task 2: Complete Ethical Considerations (Kasey, Xinyue, and Chong)
Task 3: Complete the 2nd Round Prototype & User Testing

## **Example**
 **Interview**: Aggregate questionnaire and interview data to deeper look into the problem space and domain and refine the inital design concept
- **Determine the main features and low-fidelity prototype**:  define serveral main fearures and corresponding interfaces and interactive process

# **Milestones**
Steps that need to be completed for this task:
- [ ] Step 1: Reflect the feedback from the Stand-up One ( Sep. 16)
- [ ] Step 2: Update the improved design concept and document the design process (Sep. 23)
- [x] Step 3:  Select one Ethical Considerations Template(Sep. 19)
- [ ] Step 4: Complete the Ethical Considerations WIKI Page, assigning different parts for related teammates (Sep. 28)
- [x] Step 5: Complete the 2nd Round prototype  (Sep.26 )
- [x] Step 6: Conduct User testings for the 2nd Round prototype (Sep. 28)
- [x] Step 7: Summarise and Reflect the key feedback of this user testing (Sep. 29)

**Completion Deadline:** Sep. 29

# **Documentation**
- [Home](https://github.com/motaA0309/Vitality-Ventures/wiki/)
- [Interview](https://github.com/motaA0309/Vitality-Ventures/wiki/User-Interview-Stage1)
- [Observation](https://github.com/motaA0309/Vitality-Ventures/wiki/User-Research-Observation-Stage1)
- [Low-fidelity](https://github.com/motaA0309/Vitality-Ventures/wiki/Low%E2%80%90fidelity-Prototype-and-Storyboard)
 
# **Member**
- Kexin Du (@motaA0309 ) (Kexin Du)
- Chong Xue (@heyitschang ) （Chong Xue)
- Xinyue Li (@lxy-914  ) (Xinyue Li)
- Xinyi Liao (@lxy02230423) (Xinyi Liao）
- Liuwenxuan Yan (@yanlwx) (Liuwenxuan Yan)
